### ISSUE TITLE
Error 5 on Task Execution

### ISSUE THREAD

**Issue by dautrich** [zero-24/plg_task_extensionupdates#1]
I've installed your task plugin on a testsite. To start, I configured an email even on successfull executions. That worked fine with some test executions. Afterwards, I configured a webcron service to start the execution once daily. This worked fine for another two days, when there were no updates available.
Today there were two updates available (Advanced Module Manager and Cache Cleaner). I got an e-mail about an unsuccessfull task execution:

> Hallo,
Die geplante Ausführung von Aufgabe#5, Mail bei Erweiterungs-Update, ist mit dem Exit-Code 5 um Donnerstag, 20. Juni 2024 10:50 fehlgeschlagen.
Bitte die Joomla! Administration für weitere Informationen besuchen.

In addition, I got another e-mail:

> PLG_TASK_EXTENSIONUPDATES_UPDATE_MAIL_BODY
URL:   https://www.systemtest.neudorf-mkk.de/
Site:   Neudorf
Erweiterung:   COM_ADVANCEDMODULES
Alte Version:   10.0.23
Neue Version:   10.0.24

So the update for the Advanced Module Manager was found, but not the update for the Cache Cleaner.
I (successfully) updated the Advanced Module Manager and forced a test execution of the task plugin. Again, I received an e-mail because of error 5. 
Finally, I (successfully) updated the Cache Cleaner as well.
Another test execution of the task plugin resulted in a successful termination (as there were no more updates left).

**Comment by zero-24** [comment]
Hmm interesting, I've got a few release notifications for extension updates yet, without such issues. There are only two times where I issue the "Code 5" this is when I cant find someone to inform like an super user and when there is an error while logging an error while the eMail can not be sended out. What also looks wrong to me is that you have got an email where the language string is not translated.

What languages are installed on your system? Can you see something in the logs about that time?

**Comment by brbrbr** [comment]
I ran into the issue earlier. Pure modules and template updates require a client_id as well. 

Simply removed the whole Extensionhelper and use the  $updateValue->name for all.

**Comment by dautrich** [comment]
> What languages are installed on your system? Can you see something in the logs about that time?

![grafik](https://github.com/zero-24/plg_task_extensionupdates/assets/7933215/bf0ffd57-08af-4ccb-b348-046b4b50f5fa)

**Comment by dautrich** [comment]
There are some errors "5" around related to Joomla updates (not extensions) during these days. See the discussion on Mattermost (Channel Town Square).
But I don't have the slightest idea whether there is a coincidence.

**Comment by dautrich** [comment]
> Can you see something in the logs about that time?

Here is the relevant part of the joomla_scheduler log:

2024-06-17	18:21:18	INFO	Erfolgreich abgeschlossene Aufgabe#05 in 8.96 (net 8.96) Sekunden.
2024-06-17	18:23:33	INFO	Laufende Aufgabe#05 'Mail bei Erweiterungs-Update'.
2024-06-17	18:23:42	INFO	Erfolgreich abgeschlossene Aufgabe#05 in 9.58 (net 9.58) Sekunden.
2024-06-18	10:50:15	INFO	Laufende Aufgabe#05 'Mail bei Erweiterungs-Update'.
2024-06-18	10:50:28	INFO	Erfolgreich abgeschlossene Aufgabe#05 in 12.56 (net 12.56) Sekunden.
2024-06-19	10:50:15	INFO	Laufende Aufgabe#05 'Mail bei Erweiterungs-Update'.
2024-06-19	10:50:25	INFO	Erfolgreich abgeschlossene Aufgabe#05 in 10.38 (net 10.38) Sekunden.
2024-06-20	10:50:13	INFO	Laufende Aufgabe#05 'Mail bei Erweiterungs-Update'.
2024-06-20	10:50:26	ERROR	Routine hat Ausnahme ausgelöst: `$clientId` is required when `$type` is `module`, `language` or `template` in Joomla\CMS\Extension\ExtensionHelper::getExtensionRecord()
2024-06-20	10:50:26	WARNING	Aufgabe05 wurde beendet mit Code 5 in 0.00 (net 13.13) Sekunden.

**Comment by dautrich** [comment]
Today, there is another extension update waiting. This time, it's "Schuweb Sitemap", a component.
Let's wait for the task to be executed.

**Comment by zero-24** [comment]
Ah ok than this issue will be fixed too by the PR that @brbrbr proposed. Will take a look into it today and do the release too.

**Comment by zero-24** [comment]
The release with the patch has been pushed out: https://github.com/zero-24/plg_task_extensionupdates/releases/tag/1.0.1

Thanks @brbrbr @dautrich 👍
